[profile.ci]
test-threads = "num-cpus"
fail-fast = false

[profile.ci.slow-timeout]
period = "10s"

[profile.ci-sqlite]
inherits = "ci"

[[profile.ci-sqlite.overrides]]
filter = 'test(test_generate_excel_performance)'
threads-required = "num-cpus"

[profile.ci-sqlite.junit]
path = "sqlite-test-results.xml"
report-name = "Backend tests (SQLite)"

[profile.ci-postgres]
inherits = "ci"

[profile.ci-postgres.junit]
path = "postgres-test-results.xml"
report-name = "Backend tests (Postgres)"
